models/NinjaOrder.php
<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "ninja_order".
 *
 * @property int $id
 * @property int $ninja_order_no
 * @property string $name
 * @property string $phone
 * @property string $postal_code
 * @property string $Email
 * @property string $date_create
 * @property bool $status
 */
class NinjaOrder extends \yii\db\ActiveRecord
{

    public $file;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'ninja_order';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['ninja_order_no'], 'default', 'value' => null],
            [['ninja_order_no', 'excel_id'], 'integer'],
            [['date_create'], 'safe'],
            [['status'], 'boolean'],
            [['name', 'phone', 'address', 'postal_code', 'Email'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ninja_order_no' => 'Ninja Order No',
            'name' => 'Name',
            'phone' => 'Phone',
            'postal_code' => 'Postal Code',
            'Email' => 'Email',
            'date_create' => 'Date Create',
            'status' => 'Status',
        ];
    }

    // public function uploadFile($model, $attribute)
    // {
    //     $file = UploadedFile::getInstance($model, $attribute);

    //     if($file){
    //         if($this->isNewRecord){
    //             $fileName = time().'_'.$file->baseName.'.'.$file->extension;
    //         }else{
    //             $fileName = $this->getOldAttribute($attribute);
    //         }
    //         $file->saveAs(Yii::getAlias('@webroot').'/'.$this->uploadPath.'/'.$fileName);

    //         return $fileName;
    //     }
    //     return $this->isNewRecord ? false : $this->getOldAttribute($attribute);
    // }

    
}

controllers/NinjaOrderController.php
<?php

namespace app\controllers;

use app\models\NinjaOrder;
use app\models\UploadFile;
use Yii;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * NinjaOrderController implements the CRUD actions for NinjaOrder model.
 */
class NinjaOrderController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all NinjaOrder models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => UploadFile::find()->orderBy(['create_at' => SORT_DESC]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single NinjaOrder model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    
    public function actionView($id)
    {
        $model = $this->findUploadModel($id);
        try {
            $file = Yii::getAlias('@webroot') . '/' . $model->uploadPath . '/' . $model->file;
            $inputFile = \PHPExcel_IOFactory::identify($file);
            $objReader = \PHPExcel_IOFactory::createReader($inputFile);
            $objPHPExcel = $objReader->load($file);
        } catch (Exception $e) {
            Yii::$app->session->addFlash('error', 'เกิดข้อผิดพลาด' . $e->getMessage());
        }

        $sheet = $objPHPExcel->getSheet(0);
        $highestRow = $sheet->getHighestRow();
        $highestColumn = $sheet->getHighestColumn();

        $objWorksheet = $objPHPExcel->getActiveSheet();
        foreach ($objWorksheet->getRowIterator() as $rowIndex => $row) {
            if ($rowIndex == 1) {
            } else {
                $arr[] = $objWorksheet->rangeToArray('A' . $rowIndex . ':' . $highestColumn . $rowIndex);
                $data = $objWorksheet->rangeToArray('A' . $rowIndex . ':' . $highestColumn . $rowIndex);
                foreach ($data as $value => $items) {
                    $check_data = NinjaOrder::find()->where(['ninja_order_no' => $items[0]])->one();
                    if (empty($check_data) || $check_data == null) {
                        $data_detail = new NinjaOrder();
                        $data_detail->excel_id = $model->id;
                        $data_detail->ninja_order_no = $items[0];
                        $data_detail->name = $items[1];
                        $data_detail->address = $items[2];
                        $data_detail->postal_code = $items[3];
                        $data_detail->Email = $items[4];
                        $data_detail->phone = $items[5];
                        $data_detail->date_create = date('Y-m-d H:i:s');
                        $data_detail->status = false;
                        $data_detail->save(false);
                    }
                }
            }
        }

        $dataProvider = new ArrayDataProvider([
            'allModels' => $arr,
            'pagination' => false,
        ]);

        return $this->render('view', [
            'model' => $model,
            'dataProvider' => $dataProvider,
            'allData' => $arr,
        ]);

    }

    /**
     * Creates a new NinjaOrder model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new UploadFile();

        if ($model->load(Yii::$app->request->post())) {
            $model->file = $model->uploadFile($model, 'file');
            $model->filename = $model->file;
            $model->create_at = date('Y-m-d H:i:s');
            if ($model->save(false)) {
                // return $this->redirect(['view', 'id' => $model->id]);
                return $this->actionIndex();
            } else {
                echo 'Has Problem';
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing NinjaOrder model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findUploadModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->file = $model->uploadFile($model, 'file');
            $model->save();

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing NinjaOrder model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findUploadModel($id);
        $modelNinja = NinjaOrder::find()->where(['excel_id' => $id])->all();
        @unlink(Yii::getAlias('@webroot') . '/' . $model->uploadPath . '/' . $model->file);
        if($model->delete()){
            foreach($modelNinja as $item){
                $item->delete();
            }
        }
        return $this->redirect(['index']);
    }

    /**
     * Finds the NinjaOrder model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return NinjaOrder the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = NinjaOrder::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Finds the NinjaOrder model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return UploadFile the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findUploadModel($id)
    {
        if (($model = UploadFile::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/ninja-order/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\NinjaOrder */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ninja-order-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'file')->fileInput() ?>

    <div class="form-group">
        <?= Html::submitButton('เพิ่มข้อมูล', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/ninja-order/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\NinjaOrderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ninja-order-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'ninja_order_no') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'phone') ?>

    <?= $form->field($model, 'postal_code') ?>

    <?php // echo $form->field($model, 'Email') ?>

    <?php // echo $form->field($model, 'date_create') ?>

    <?php // echo $form->field($model, 'status')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/ninja-order/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\NinjaOrder */

$this->title = 'Create Ninja Order';
$this->params['breadcrumbs'][] = ['label' => 'Ninja Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ninja-order-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/ninja-order/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\data\ActiveDataProvider;
/* @var $this yii\web\View */
/* @var $searchModel app\models\NinjaOrderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Ninja Orders';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ninja-order-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Ninja Order', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'file',
                'label' => 'ไฟล์'
            ],
            [
                'attribute' => 'create_at',
                'label' => 'สร้างเมื่อวันที่'

            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Actions',
                'headerOptions' => ['style' => 'width: 80px;'],
                'template' => '{view} {delete}',
                'visibleButtons' => [
                    'view' => function ($url, $data, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye"></span>', \yii\helpers\Url::to(['/ninja-order/view', 'id' => $model['id']]));
                    },
                    'delete' => function ($url, $model, $key) {
                            return Html::a('<i class="glyphicon glyphicon-trash"></i>', ['/ninja-order/delete', 'id' => $model['id']], [
                                'data' => [
                                    'confirm' => 'คุณต้องการลบรายการนี้หรือไม่',
                                    'method' => 'post',
                                ],
                            ]);
                    }
                ]
            ]
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

views/ninja-order/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\NinjaOrder */

$this->title = 'Update Ninja Order: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Ninja Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="ninja-order-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/ninja-order/view.php
<?php

use kartik\select2\Select2;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\NinjaOrder */

// var_dump($allData);
// exit();

$this->title = $model->filename;
$this->params['breadcrumbs'][] = ['label' => 'Ninja Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="ninja-order-view">
    <h1><?=Html::encode($this->title)?></h1>

    <?php $form = ActiveForm::begin(['action' => ['replace/prepare-print'], 'options'=>['target'=>'_blank']])?>
    <h2>Option</h3>
    <div class='col-md-6''>
        <h3>Product Weight</h3>
        <div class="form-group">
            <span><?=Select2::widget([
    'name' => 'size',
    'data' => $model->sizeWeight(),
    'pluginOptions' => [
        'allowClear' => true,
    ],
]);?></span>
        </div>
    </div>
    <div class='col-md-6'>
        <h3>Print Option</h3>
        <div class="form-group">
            <span><?=Select2::widget([
    'name' => 'papersize',
    'data' => $model->optionPaper(),
    'pluginOptions' => [
        'allowClear' => true,
    ],
]);?>
        </span>
           </div>
    </div>

    <?php echo Html::hiddenInput('excelid', $model->id); ?>

    <div class="col-md-12">
       <?=Html::submitButton('Generate Print', ['class' => 'btn btn-success'])?>
    </div>

    <?php ActiveForm::end();?>

<br>


<div class='col-md-12' style='margin-top: 10px'>
<?=GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        [
            'label' => 'Ninja Order No',
            'value' => function ($model) {
                return $model[0][0];
            },
        ],
        [
            'label' => 'Name',
            'value' => function ($model) {
                return $model[0][1];
            },
        ],
        [
            'label' => 'Address',
            'value' => function ($model) {
                return $model[0][2];
            },
        ],
        [
            'label' => 'Postal Code ',
            'value' => function ($model) {
                return $model[0][3];
            },
        ],
        [
            'label' => 'Email',
            'value' => function ($model) {
                return $model[0][4];
            },
        ],
        [
            'label' => 'Contact',
            'value' => function ($model) {
                return $model[0][5];
            },
        ],
    ],
])?>
</div>


</div>