models/School.php
<?php

namespace app\models;

use Yii;
use yii\helpers\Json;

/**
 * This is the model class for table "school".
 *
 * @property int $id
 * @property string $name
 * @property string $address
 */
class School extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'school';
    }

   public  $road,$sub_district,$district,$province,$zip_code,$phone,$tax_id;

    public function rules()
    {
        return [
           [['road','sub_district','district','province','zip_code','phone','tax_id','address'],'safe'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'ชื่อโรงเรียน',
            'road'=>'ถนน',
            'sub_district'=>'ตำบล / แขวง',
            'district'=>'อำเภอ / เขต',
            'province'=>'จังหวัด',
            // 'zip_code'=>'รหัส',
            'phone'=>'เบอร์',
            'zip_code'=>'รหัสไปรษณีย์',
            'address' => 'ที่อยู่',
        ];
    }
    public function getAddress($address, $road,$sub_district,$district,$province,$zip_code,$phone,$tax_id)
    {
        $dataArray = [];
        $dataArray['address'] = !empty($address) ? $address : '';
        $dataArray['road'] = !empty($road) ? $road : '';
        $dataArray['sub_district'] = !empty($sub_district) ? $sub_district : '';
        $dataArray['district'] = !empty($district) ? $district : '';
        $dataArray['province'] = !empty($province) ? $province : '';
        $dataArray['zip_code'] = !empty($zip_code) ? $zip_code : '';
        $dataArray['phone'] = !empty($phone) ? $phone : '';
        $dataArray['tax_id'] = !empty($tax_id) ? $tax_id : '';
        return Json::encode($dataArray);
    }
    public function getShowAddress($data){

        $model = Json::decode($data,true);
        $data=' '.!empty($model['address'])?' <b>ที่อยู่.</b> '.$model['address']:' ';
        $data.=' '.!empty($model['road'])?' <b>ถนน.</b> '.$model['road']:' ';
        $data.=' '.!empty($model['sub_district'])?' <b>ต.</b> '.$model['sub_district']:' ';
        $data.=' '.!empty($model['district'])?' <b>อ.</b> '.$model['district']:' ';

        $data.=' '.!empty($model['province'])?' <b>จ.</b> '.$model['province']:' ';
        $data.=' '.!empty($model['zip_code'])?' <b>รหัสไปรษณีย์</b> '.$model['zip_code']:' ';
        $data.=' โทร'.!empty($model['phone'])?$model['phone']:'';
        return $data;

    }
}

controllers/SchoolController.php
<?php

namespace app\controllers;

use app\models\Customer;
use yii\helpers\Json;
use yii\helpers\Url;
use Mpdf\Mpdf;
use Yii;
use app\models\School;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SchoolController implements the CRUD actions for School model.
 */
class SchoolController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all School models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => School::find()->orderBy('id desc'),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single School model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $customer = new  Customer();
        if ($customer->load(Yii::$app->request->post())) {
            $customer->school_id = $id;
            $customer->save();
            return $this->refresh();
        }
        return $this->render('view', [
            'customer' => $customer,
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new School model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new School();
        $post=Yii::$app->request->post();
        if ($model->load($post)) {
            $model->address = $model->getAddress($model['address'], $model['road'], $post['sub_district'], $post['district'], $post['province'], $post['zip_code'], $model['phone'], $model['tax_id']);
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionGetSchool()
    {
        $data = json_decode(file_get_contents("http://scb.futuremlm.com/api/schools"), true);
        $dataSchool = \yii\helpers\ArrayHelper::map($data, 'id', 'name');
        foreach ($data as $mo) {
            $model = new School();
            $model->name = $mo['name'];
            $model->save();
        }
        echo 'ok';
    }

    /**
     * Updates an existing School model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load($post=Yii::$app->request->post())) {
            $model->address = $model->getAddress($model['address'], $model['road'], $post['sub_district'], $post['district'], $post['province'], $post['zip_code'], $model['phone'], $model['tax_id']);
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionCustomer()
    {

        return $this->render('customer');
    }

    /**
     * Deletes an existing School model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionDeleteCus($id, $page)
    {
        Customer::findOne($id)->delete();
        return $this->redirect(['view', 'id' => $page]);
    }

    public function actionPrint($id, $page)
    {
        $data_school=School::findOne(['id'=>$page]);
        $customer= Json::decode($data_school->address,true);
        $user =Customer::findOne(['id'=>$id]);
        $params = Yii::$app->params;
        $fontDirs = $params['defaultConfig']['fontDir'];
        $fontData = $params['defaultFontConfig']['fontdata'];
        $mpdf = new Mpdf([
            'fontDir' => array_merge($fontDirs, [
                Url::base() . 'fonts/THSarabun',
            ]),
            'fontdata' => $fontData + [
                    'thsarabun' => [
                        'R' => 'THSarabun.ttf',
                        'B' => 'THSarabun Bold.ttf',
                        'I' => 'THSarabun Italic.ttf',
                        'BI' => 'THSarabun BoldItalic.ttf',
                    ]
                ],
//            'default_font_size' => 10,
            'default_font' => 'thsarabun',
            'mode' => 'utf-8',
            'format' => [110, 235],
            'language' => 'th',
            'margin_top' => 10,
            'margin_left' => 30,
            'margin_right' => 15,
            'margin_bottom' => 10,
            'mirrorMargins' => true,
            'orientation' => 'L',
        ]);
        $stylesheet = file_get_contents(Url::base() . 'css/letterStyle.css');
//        $mpdf->Image(Url::base() .'img/NGLogo.jpg', 90, 90, 0, 0, 'jpg', '', true, false);
        $mpdf->WriteHTML($stylesheet, 1);
        $mpdf->WriteHTML($this->renderPartial('letter', [
            'customer' => $customer,'user'=>$user,'data_school'=>$data_school]), 2);
        $filename = 'letter_' . $id . '.pdf';
        $path = Yii::getAlias('@app') . DIRECTORY_SEPARATOR . 'file_print' . DIRECTORY_SEPARATOR;
        $mpdf->Output();
//        $mpdf->Output($path . $filename, 'F');
//        $py = Yii::getAlias('@app') . DIRECTORY_SEPARATOR . 'web' . DIRECTORY_SEPARATOR . 'python' . DIRECTORY_SEPARATOR . 'auto_print.py';
//        $read = exec("python3 " . $py . " " . $path . " " . $filename . " " . 2);
    }

    /**
     * Finds the School model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return School the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = School::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/school/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\School */
/* @var $form yii\widgets\ActiveForm */
?>
<?php
$this->registerCssFile('@web/js/type.js/dist/jquery.Thailand.min.css', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/type.js/dependencies/zip.js/zip.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/type.js/dependencies/JQL.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/type.js/dependencies/typeahead.bundle.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/type.js/dist/jquery.Thailand.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/type.js/app.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
?>
<div class="school-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

<div class="row">
    <div class="col-md-3">
        <?= $form->field($model, 'address')->textInput() ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($model, 'road')->textInput() ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($model, 'sub_district')->textInput(['name'=>'sub_district']) ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($model, 'district')->textInput(['name'=>'district']) ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($model, 'province')->textInput(['name'=>'province']) ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($model, 'zip_code')->textInput(['name'=>'zip_code']) ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($model, 'tax_id')->textInput() ?>
    </div>
</div>
    <div class="form-group text-right">
        <?= Html::submitButton('บันทึก', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php
$data =Yii::getAlias('@web/js/db.json');
$this->registerJs('
$.Thailand({
    database: "'.$data.'",
    $district: $(\'#w0 [name="sub_district"]\'),
    $amphoe:$( "input[name=\'district\']" ),
    $province: $(\'[name="province"]\'),
    $zipcode: $(\'[name="zip_code"]\'),

    onDataFill: function(data){
        console.info(\'Data Filled\', data);
    },

    onLoad: function(){
        console.info(\'Autocomplete is ready!\');
        $(\'#loader, .demo\').toggle();
    }
});
')
?>

views/school/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\School */

$this->title = 'Create School';
$this->params['breadcrumbs'][] = ['label' => 'Schools', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="school-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/school/customer.php
<?php
$this->registerCssFile('@web/js/type.js/dist/jquery.Thailand.min.css', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/type.js/dependencies/zip.js/zip.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/type.js/dependencies/JQL.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/type.js/dependencies/typeahead.bundle.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/type.js/dist/jquery.Thailand.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/type.js/app.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
?>
<div class="uk-container uk-padding">

    <!-- DEMO 1 -->
    <h1>Auto Complete ที่อยู่ </h1>

    <div id="loader">
        <div uk-spinner></div> รอสักครู่ กำลังโหลดฐานข้อมูล...
    </div>

    <form id="demo1" class="demo" style="display:none;" autocomplete="off" uk-grid >

        <div class="uk-width-1-2@m">
            <label class="h2">ตำบล / แขวง</label>
            <input name="district" class="uk-input uk-width-1-1" type="text">
        </div>

        <div class="uk-width-1-2@m">
            <label class="h2">อำเภอ / เขต</label>
            <input name="amphoe" class="uk-input uk-width-1-1" type="text">
        </div>

        <div class="uk-width-1-2@m">
            <label class="h2">จังหวัด</label>
            <input name="province" class="uk-input uk-width-1-1" type="text">
        </div>

        <div class="uk-width-1-2@m">
            <label class="h2">รหัสไปรษณีย์</label>
            <input name="zipcode" class="uk-input uk-width-1-1" type="text">
        </div>

    </form>



<?php
$data =Yii::getAlias('@web/js/db.json');
$this->registerJs('
$.Thailand({
    database: "'.$data.'",
    $district: $(\'#demo1 [name="district"]\'),
    $amphoe: $(\'#demo1 [name="amphoe"]\'),
    $province: $(\'#demo1 [name="province"]\'),
    $zipcode: $(\'#demo1 [name="zipcode"]\'),

    onDataFill: function(data){
        console.info(\'Data Filled\', data);
    },

    onLoad: function(){
        console.info(\'Autocomplete is ready!\');
        $(\'#loader, .demo\').toggle();
    }
});
')
?>

views/school/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Json;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Schools';
$this->params['breadcrumbs'][] = $this->title;
$school = new  \app\models\School();
if ($post = (Yii::$app->request->post())) {
    $school->id = $post['School']['id'];
    $data_select = \app\models\School::findOne(['id' => $post['School']['id']]);
}
?>
<div class="school-index">
    <?php Pjax::begin(); ?>
    <div class="text-right">
        <?= Html::a('เพิ่มโรเรียน', ['create'], ['class' => 'btn btn-success']) ?>
    </div>
    <?php GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            // 'id',
            'name',
//                'address:ntext',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

    <div class="row">
        <div class="col-md-4">
            <?php $form = \yii\widgets\ActiveForm::begin(['action' => 'customer', 'method' => 'post']); ?>
            <?= Select2::widget([
                'language' => 'th',
                'model' => $school,
                'attribute' => 'name',
                'data' => \yii\helpers\ArrayHelper::map(\app\models\School::find()->all(), 'id', 'name'),
                'options' => ['placeholder' => 'ค้นหาโรงเรียน...'],
                'pluginEvents' => [
                    "select2:select" => "function (e) { 
                        var data = e.params.data;
                         console.log(data);
                          location.href = 'view?id='+data.id
                     }",
                    "select2:unselect" => "function() {
                                 location.href = 'index'
                          }"
                ],
                'pluginOptions' => [
                    'allowClear' => true,
                    //'minimumInputLength' => 2,
                ],
            ]); ?>
            <?php \yii\widgets\ActiveForm::end(); ?>
            <?php echo  GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    // 'id',
                    'name',
//                'address:ntext',
                    ['class' => 'yii\grid\ActionColumn','template' => '{view} {delete}'],
                ],
            ]); ?>
        </div>
        <div class="col-md-8">



        </div>
    </div>


    <?php Pjax::end(); ?>
</div>

views/school/letter.php
<?php
$value = ["name"=>"บริษัท เนกเจนซอฟ จํากัด (สำนักงานใหญ่)","address"=>"เลขที่ 1558/41","road"=>"ถ.บางนา-ตราด","sub_district"=>"แขวงบางนา","district"=>"เขตบางนา","province"=>"กรุงเทพฯ","zip_code"=>"10260","phone"=>"021014822","tax_id"=>"0105559127204"]



?>

<div style="height: 50px">
    <div style="width: 5%;display: inline; float: left">
        <img src="img/NGLogo.jpg" style="width: 30px; height: 30px;">
    </div>
    <div style="display: inline; float: left">
        <span style="font-size: 20px; font-weight: Bold; font-style: Italic">NextSchool<span style="font-style: normal">
                <?= $value['name'] ?> </span></span><br>
    </div>
    <div>
        <span style="font-size: 20px"> <?= !empty($value['address'])?$value['address']:'-'?>
            <?= !empty($value['road'])?$value['road']:'-'?>
            <?=!empty($value['sub_district'])?$value['sub_district']:'-'?>
            <?=!empty($value['district'])?$value['district']:'-' ?></span><br>
        <span style="font-size: 20px">
            <?=!empty($value['province'])?$value['province']:'-' ?>&nbsp;<?= !empty($value['zip_code'])?$value['zip_code']:'-'?>&nbsp;
            <?=  !empty($value['phone'])?"โทร.".$value['phone']:'-'?></span>
    </div>
</div>
<br>
<div style="margin-left: 250px; margin-right: 20px; height: 150px">
    <p style="font-size: 26px; margin-top: 0px; font-weight: bold;">กรุณาส่ง <br>
        <span style="font-size: 24px; font-weight: normal">
            <?= !empty($user['name'])?$user['name']:' '?>&nbsp;<span
                style="font-weight: bold"><?=  !empty($user['tel'])?' โทร.'.$user['tel']:' ' ?><br></span>
            <?php if(!empty($data_school->name)):?>
            <span style="font-size: 24px; font-weight: normal"> <?= 'โรงเรียน'.$data_school->name?>&nbsp;</span>
            <br></span>
        <?php endif;?>
        <?php if(!empty($customer)):?>
        <span style="font-size: 24px; font-weight: normal">
            <?=!empty( $customer['address'])? ' '.$customer['address']:' '?> </span>
        <span style="font-size: 24px; font-weight: normal">
            <?=!empty( $customer['road'])? 'ถนน.'.$customer['road']:' '?> </span>
        <span style="font-size: 24px; font-weight: normal">
            <?=!empty( $customer['district'])? 'ต. '.$customer['district']:' '?> <br></span>
        <span style="font-size: 24px; font-weight: normal">
            <?=!empty( $customer['district'])? 'อ. '.$customer['district']:' '?> </span>
        <span style="font-size: 24px; font-weight: normal">
            <?=!empty( $customer['province'])? 'จ. '.$customer['province']:' '?> </span>
        <br />
        <span style="font-size: 26px; font-weight: bold">
            <?=!empty( $customer['zip_code'])? ' '.$customer['zip_code']:' '?> </span>
        <?php endif;?>
    </p>
</div>

views/school/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\School */

$this->title = 'Update School: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Schools', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="school-update">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php
       $mock= \yii\helpers\Json::decode( $model->address,true);
    $model->address = $mock['address'];
    $model->road = $mock['road'];
    $model->sub_district = $mock['sub_district'];
    $model->district = $mock['district'];
    $model->province = $mock['province'];
    $model->zip_code = $mock['zip_code'];
    $model->phone = $mock['phone'];
    $model->tax_id = $mock['tax_id'];
    ?>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/school/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\School */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Schools', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

use yii\widgets\ActiveForm;
use yii\data\ActiveDataProvider;

?>
<div class="school-view">
    <h2><?= Html::encode($this->title) ?></h2>
    <div class="row">
        <div class="col-md-5">
            <p>
                <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary btn-sm']) ?>
                <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger btn-sm',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ]) ?>
            </p>
        </div>
        <div class="col-md-7">
            <div class="row">
                <?php $form = ActiveForm::begin(); ?>
                <div class="col-md-5">
                    <?= $form->field($customer, 'name')->textInput() ?>
                </div>
                <div class="col-md-4">
                    <?= $form->field($customer, 'tel')->textInput() ?>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <br>
                        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
                    </div>
                </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-4">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'name',
                  [
                          'attribute'=>'address',
                          'format'=>'raw',
                          'value'=>function($model){
                                return $model->getShowAddress($model['address']);
                          }
                  ]
                ],
            ]) ?>
        </div>
        <div class="col-md-8">
            <?php
            $dataProvider = new ActiveDataProvider([
                'query' => \app\models\Customer::find()->where(['school_id' => $model->id]),
            ]);
            ?>
            <?php echo \yii\grid\GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    // 'id',
                    'name',
                    'tel',
//                'address:ntext',
                    ['class' => 'yii\grid\ActionColumn', 'template' => '{print} {delete-cus}',
                        'buttons' => [
                            'print' => function ($url,$data) {
                                return Html::a('<i class="glyphicon glyphicon-envelope"></i>', ['school/print','id'=>$data['id'],'page'=>$data['school_id']], ['target' => '_blank']);
                            },
                            'delete-cus' => function ($url,$data) {
                                return Html::a('<i class="glyphicon glyphicon-trash"></i>', ['school/delete-cus','id'=>$data['id'],'page'=>$data['school_id']]);
                            }
                        ]
                    ],
                ],
            ]); ?>
        </div>
    </div>


</div>